openapi: 3.0.0
info:
  title: Image manipulation API
  description: API that takes a png or jpeg image in base64 and returns a manipulated image based on user request by Chad R. Stewart *Note that the base64 images in the examples is dummy data for show. You'll need to find your own base64 image string.
  contact:
    name: Chad R. Stewart
    url: https://www.twitter.com/Chad_R_Stewart
  version: 1.0.0
servers:
  - url: https://localhost:3000
paths:
  /image/resize/:
    description: Resize a png image
    post:
      description: Takes an image with a percentage scale between 1 - 99 and returns the image to that scale
      tags:
        - resize
      parameters:
        - in: JSON
          name: percentageScale
          schema:
            type: number
          required: true
          description: The percentage it will scale to. This number must be between 1 - 99.
        - in: JSON
          name: base64String
          schema:
            type: string
          required: true
          description: The base64String that will be decoded and turned into an image.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - percentageScale
                - base64String
              properties:
                percentageScale:
                  type: number
                  description: The scale between 1 - 99 in which the book can be resized.
                base64String:
                  type: string
                  description: The image as a base64 string
              example:
                percentageScale: 40
                base64String: data:image/jpeg;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: true
                  message: "data:image/jpeg;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="

        400:
          description: This is not a properly formatted base64 image
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "This is not a properly formatted base64 image"
        415:
          description: Please send an image that is .jpg, .jpeg, .jpe or .png
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "Please send an image that is .jpg, .jpeg, .jpe or .png"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "There was an internal server error"
  /image/grayscale:
    description: Makes an image grayscale
    post:
      description: Takes an image returns the image in grayscale
      tags:
        - grayscale
      parameters:
        - in: JSON
          name: base64String
          schema:
            type: string
          required: true
          description: The base64String that will be decoded and turned into an image.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - base64String
              properties:
                base64String:
                  type: string
                  description: The image as a base64 string
              example:
                base64String: data:image/jpeg;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: true
                  message: "data:image/jpeg;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="

        400:
          description: This is not a properly formatted base64 image
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "This is not a properly formatted base64 image"
        415:
          description: Please send an image that is .jpg, .jpeg, .jpe or .png
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "Please send an image that is .jpg, .jpeg, .jpe or .png"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "There was an internal server error"
  /image/transformation:
    description: Transforms an image
    post:
      description: Takes an image with a transformation type and parameters on how to conduct that transformation and returns an image based on those specifications
      tags:
        - transformation
      parameters:
        - in: JSON
          name: transformationSpecs
          schema:
            type: object
            properties:
              resizeScale:
                type: number
              rotation:
                type: number
              xAxisFlip:
                type: boolean
              yAxisFlip:
                type: boolean
          required: true
          description: transformationSpecs is required and at least one transformation must be defined.
        - in: JSON
          name: base64String
          schema:
            type: string
          required: true
          description: The base64String that will be decoded and turned into an image.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - transformationSpecs
                - base64String
              properties:
                transformation-specs:
                  type: object
                  description: specifications on the transformation based on the type
                base64String:
                  type: string
                  description: The image as a base64 string
              example:
                transformationSpecs: { "resizeScale": 40, "rotation": 60, "xAxisFlip": true, "yAxisFlip": true }
                base64String: data:image/jpeg;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: true
                  message: "data:image/jpeg;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="

        400:
          description: This is not a properly formatted base64 image
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "This is not a properly formatted base64 image"
        415:
          description: Please send an image that is .jpg, .jpeg, .jpe or .png
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "Please send an image that is .jpg, .jpeg, .jpe or .png"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "There was an internal server error"
  /image/blur:
    description: Add a blur to an image
    post:
      description: Takes an image returns the image in blur
      tags:
        - blur
      parameters:
        - in: JSON
          name: base64String
          schema:
            type: string
          required: true
          description: The base64String that will be decoded and turned into an image.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - base64String
              properties:
                base64String:
                  type: string
                  description: The image as a base64 string
              example:
                base64String: data:image/jpeg;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: true
                  message: "data:image/jpeg;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="

        400:
          description: This is not a properly formatted base64 image
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "This is not a properly formatted base64 image"
        415:
          description: Please send an image that is .jpg, .jpeg, .jpe or .png
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "Please send an image that is .jpg, .jpeg, .jpe or .png"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "There was an internal server error"
  /image/negate:
    description: Negates the colors of an image
    post:
      description: Takes an image returns the image in negate
      tags:
        - negate
      parameters:
        - in: JSON
          name: base64String
          schema:
            type: string
          required: true
          description: The base64String that will be decoded and turned into an image.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - base64String
              properties:
                base64String:
                  type: string
                  description: The image as a base64 string
              example:
                base64String: data:image/jpeg;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: true
                  message: "data:image/jpeg;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="

        400:
          description: This is not a properly formatted base64 image
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "This is not a properly formatted base64 image"
        415:
          description: Please send an image that is .jpg, .jpeg, .jpe or .png
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "Please send an image that is .jpg, .jpeg, .jpe or .png"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "There was an internal server error"